include "bird-common.conf";


protocol static DEFAULT4 {
	ipv4 { preference 110; };
	route 0.0.0.0/0 blackhole;
}

protocol static DEFAULT6 {
	ipv6 { preference 110; };
	route 0::/0 blackhole;	
}

# Do not sync blackhole routes into OS kernel.
# Export everything (VIP routes) learned through BGP neighbors.
filter gw_kernel_export {
	if source = RTS_STATIC && dest = RTD_BLACKHOLE then reject;
	else accept;
}

filter bgp_announce {
	if ( net ~ [ 0.0.0.0/0 ] ) then accept;
	if ( net ~ [ 0::/0 ] ) then accept;
	if source = RTS_STATIC && dest = RTD_BLACKHOLE then accept;
	else reject;
}

protocol kernel {
	ipv4 {
		import none;
		export filter gw_kernel_export;
	};
	merge paths on;
}

protocol kernel {
	ipv6 {
		import none;
		export filter gw_kernel_export;
	};
	merge paths on;
}


# ns-a gw-a1 peers on VLAN 100 (ASN 8103)
protocol bgp GW4_A1 from LINK {
	local 169.254.100.150 port 10179 as 4248829953;
	neighbor range 0.0.0.0/0 port 10179 as 8103;
	dynamic name "GW4_A1_";
	ipv4 {
		import all;
		export filter bgp_announce;
	};
}

protocol bgp GW6_A1 from LINK {
	local fd00:100::150 port 10179 as 4248829953;
	neighbor range 0::/0 port 10179 as 8103;
	dynamic name "GW6_A1_";
	ipv6 {
		import all;
		export filter bgp_announce;
	};
}

# ns-a gw-a2 peers on VLAN 200 (ASN 8104)
protocol bgp GW4_A2 from LINK {
	local 169.254.200.150 port 10179 as 4248829953;
	neighbor range 0.0.0.0/0 port 10179 as 8104;
	dynamic name "GW4_A2_";
	ipv4 {
		import all;
		export filter bgp_announce;
	};
}

protocol bgp GW6_A2 from LINK {
	local fd00:200::150 port 10179 as 4248829953;
	neighbor range 0::/0 port 10179 as 8104;
	dynamic name "GW6_A2_";
	ipv6 {
		import all;
		export filter bgp_announce;
	};
}

# ns-b gw-b1 peers on VLAN 300 (ASN 8105)
protocol bgp GW4_B1 from LINK {
	local 169.254.101.150 port 10179 as 4248829953;
	neighbor range 0.0.0.0/0 port 10179 as 8105;
	dynamic name "GW4_B1_";
	ipv4 {
		import all;
		export filter bgp_announce;
	};
}

protocol bgp GW6_B1 from LINK {
	local fd00:300::150 port 10179 as 4248829953;
	neighbor range 0::/0 port 10179 as 8105;
	dynamic name "GW6_B1_";
	ipv6 {
		import all;
		export filter bgp_announce;
	};
}

# ns-b gw-b2 peers on VLAN 400 (ASN 8106)
protocol bgp GW4_B2 from LINK {
	local 169.254.201.150 port 10179 as 4248829953;
	neighbor range 0.0.0.0/0 port 10179 as 8106;
	dynamic name "GW4_B2_";
	ipv4 {
		import all;
		export filter bgp_announce;
	};
}

protocol bgp GW6_B2 from LINK {
	local fd00:400::150 port 10179 as 4248829953;
	neighbor range 0::/0 port 10179 as 8106;
	dynamic name "GW6_B2_";
	ipv6 {
		import all;
		export filter bgp_announce;
	};
}
