include "bird-common.conf";
include "bird-filler-net.conf";


# Register below routes into BIRD through static blackhole routes.
# They will get announced to BGP neighbors with a local next-hop IP
# (refer to "next hop self"). They will serve as cluster breakout routes
# on the cluster side.
# note: in kernel protocol forbid syncing these into OS routing table
protocol static NET4_1 {
	ipv4 { preference 100; };
	route 169.254.0.0/16 blackhole;
}

protocol static NET4_2 {
        ipv4 { preference 100; };
        route 200.100.0.0/16 blackhole;
}

protocol static NET6_1 {
	ipv6 { preference 100; };
	route fd00:100::/32 blackhole;
}

protocol static NET6_2 {
        ipv6 { preference 100; };
        route fd00:200::/32 blackhole;
}

# Do not sync above backhole routes into OS kernel.
# But export everything (VIP routes) learned through BGP neighbors
# into OS kernel.
filter gw_kernel_export {
	if source = RTS_STATIC && dest = RTD_BLACKHOLE then reject;
	else accept;
}

# With this config routes that are supposed to get announced by
# local BGP are configured as static blackhole routes in BIRD.
filter bgp_announce {
	if ( net ~ [ 0.0.0.0/0 ] ) then accept;
	if ( net ~ [ 0::/0 ] ) then accept;
        if source = RTS_STATIC && dest = RTD_BLACKHOLE then accept;
	else reject;
}

protocol kernel {
	ipv4 {
		import none;
		export filter gw_kernel_export;
	};
	merge paths on;
}

protocol kernel {
	ipv6 {
		import none;
		export filter gw_kernel_export;
	};
	merge paths on;
}


# ns-a peers on VLAN 100 (ASN 8103)
protocol bgp GW4_NSA from LINK {
	local port 10179 as 4248829953;
	neighbor range 0.0.0.0/0 port 10179 as 8103;
	dynamic name "GW4_NSA_";
	ipv4 {
		import all;
		export filter bgp_announce;
	};
}

protocol bgp GW6_NSA from LINK {
	local port 10179 as 4248829953;
	neighbor range 0::/0 port 10179 as 8103;
	dynamic name "GW6_NSA_";
	ipv6 {
		import all;
		export filter bgp_announce;
	};
}

# ns-b peers on VLAN 200 (ASN 8104)
protocol bgp GW4_NSB from LINK {
	local port 10179 as 4248829953;
	neighbor range 0.0.0.0/0 port 10179 as 8104;
	dynamic name "GW4_NSB_";
	ipv4 {
		import all;
		export filter bgp_announce;
	};
}

protocol bgp GW6_NSB from LINK {
	local port 10179 as 4248829953;
	neighbor range 0::/0 port 10179 as 8104;
	dynamic name "GW6_NSB_";
	ipv6 {
		import all;
		export filter bgp_announce;
	};
}
