include "bird-common.conf";


protocol static DEFAULT4 {
	ipv4 { preference 110; };
	route 0.0.0.0/0 blackhole;
}

# Do not sync blackhole routes into OS kernel.
# Export everything (VIP routes) learned through BGP neighbors.
filter gw_kernel_export {
	if source = RTS_STATIC && dest = RTD_BLACKHOLE then reject;
	else accept;
}

filter bgp_announce {
	if ( net ~ [ 0.0.0.0/0 ] ) then accept;
	if source = RTS_STATIC && dest = RTD_BLACKHOLE then accept;
	else reject;
}

protocol kernel {
	ipv4 {
		import none;
		export filter gw_kernel_export;
	};
	merge paths on;
}


# separate-appnetwork gw-a1 peers on VLAN 100 (ASN 64512)
protocol bgp GW4_A1 from LINK {
	local 169.254.100.150 port 10179 as 4200000000;
	neighbor range 0.0.0.0/0 port 10179 as 64512;
	dynamic name "GW4_A1_";
	ipv4 {
		import all;
		export filter bgp_announce;
	};
}

# separate-appnetwork gw-a2 peers on VLAN 200 (ASN 64513)
protocol bgp GW4_A2 from LINK {
	local 169.254.200.150 port 10179 as 4200000000;
	neighbor range 0.0.0.0/0 port 10179 as 64513;
	dynamic name "GW4_A2_";
	ipv4 {
		import all;
		export filter bgp_announce;
	};
}

# common-appnetwork gw-b1 peers on VLAN 300 (ASN 64514)
protocol bgp GW4_B1 from LINK {
	local 169.254.101.150 port 10179 as 4200000000;
	neighbor range 0.0.0.0/0 port 10179 as 64514;
	dynamic name "GW4_B1_";
	ipv4 {
		import all;
		export filter bgp_announce;
	};
}

# common-appnetwork gw-b2 peers on VLAN 400 (ASN 64515)
protocol bgp GW4_B2 from LINK {
	local 169.254.201.150 port 10179 as 4200000000;
	neighbor range 0.0.0.0/0 port 10179 as 64515;
	dynamic name "GW4_B2_";
	ipv4 {
		import all;
		export filter bgp_announce;
	};
}

# sctp-multihoming path 1 on VLAN 500 (ASN 64516)
protocol bgp GW4_SCTP1 from LINK {
	local 169.254.102.150 port 10179 as 4200000000;
	neighbor range 0.0.0.0/0 port 10179 as 64516;
	dynamic name "GW4_SCTP1_";
	ipv4 {
		import all;
		export filter bgp_announce;
	};
}

# sctp-multihoming path 2 on VLAN 600 (ASN 64517)
protocol bgp GW4_SCTP2 from LINK {
	local 169.254.202.150 port 10179 as 4200000000;
	neighbor range 0.0.0.0/0 port 10179 as 64517;
	dynamic name "GW4_SCTP2_";
	ipv4 {
		import all;
		export filter bgp_announce;
	};
}
