log stderr all;

protocol device {}

protocol bfd {
	interface "*" {
		passive on;
	};
}

protocol kernel {
	ipv4 {
		import none;
		export all;
	};
}

protocol kernel {
	ipv6 {
		import none;
		export all;
	};
}

protocol static EXTERNAL_ROUTES {
	ipv4 { preference 100; };
	route 100.64.0.0/24 blackhole;
	route 100.64.1.0/24 blackhole;
	route 100.64.2.0/24 blackhole;
}

protocol static EXTERNAL_ROUTES6 {
	ipv6 { preference 100; };
	route fd00:64::/64 blackhole;
	route fd00:65::/64 blackhole;
}

protocol static DEFAULT4 {
	ipv4 { preference 110; };
	route 0.0.0.0/0 blackhole;
}

protocol static DEFAULT6 {
	ipv6 { preference 110; };
	route 0::/0 blackhole;
}

filter bgp_announce {
	if ( net ~ [ 0.0.0.0/0 ] ) then accept;
	if ( net ~ [ 0::/0 ] ) then accept;
	if source = RTS_STATIC && dest = RTD_BLACKHOLE then accept;
	else reject;
}

template bgp LINK {
	debug {events, states};
	direct;
	hold time 24;
	bfd on;
	graceful restart off;
	ipv4 {
		import all;
		export filter bgp_announce;
		next hop self;
	};
	ipv6 {
		import all;
		export filter bgp_announce;
		next hop self;
	};
}

# ns-a peers on VLAN 100 (169.254.100.x / fd00:100::x)
protocol bgp nsa_v4 from LINK {
	interface "vlan1";
	local 169.254.100.150 port 10179 as 4248829953;
	neighbor 169.254.100.1 port 10179 as 8103;
}

protocol bgp nsa_v6 from LINK {
	interface "vlan1";
	local fd00:100::150 port 10179 as 4248829953;
	neighbor fd00:100::1 port 10179 as 8103;
}

# ns-b peers on VLAN 200 (169.254.200.x / fd00:200::x)
protocol bgp nsb_v4 from LINK {
	interface "vlan2";
	local 169.254.200.150 port 10179 as 4248829953;
	neighbor 169.254.200.1 port 10179 as 8104;
}

protocol bgp nsb_v6 from LINK {
	interface "vlan2";
	local fd00:200::150 port 10179 as 4248829953;
	neighbor fd00:200::1 port 10179 as 8104;
}
