services:
  vpn-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vpn-gateway
    privileged: true
    command: /init.sh
    networks:
      - kind

networks:
  kind:
    name: kind
    external: true
