apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manager.yaml
- ../templates

images:
- name: controller-manager
  newName: registry.nordix.org/cloud-native/meridio-2/controller-manager
  newTag: test
