# This rule is not used by the project meridio-2 itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the meridio-2.nordix.org.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: meridio-2
    app.kubernetes.io/managed-by: kustomize
  name: distributiongroup-editor-role
rules:
- apiGroups:
  - meridio-2.nordix.org
  resources:
  - distributiongroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - meridio-2.nordix.org
  resources:
  - distributiongroups/status
  verbs:
  - get
