## Append samples of your project ##
resources:
- meridio-2_v1alpha1_gatewayconfig.yaml
- meridio-2_v1alpha1_customservice.yaml
- meridio-2_v1alpha1_l34route.yaml
- meridio-2_v1alpha1_gatewayrouter.yaml
- meridio-2_v1alpha1_endpointnetworkconfiguration.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
