apiVersion: meridio-2.nordix.org/v1alpha1
kind: GatewayRouter
metadata:
  labels:
    app.kubernetes.io/name: meridio-2
    app.kubernetes.io/managed-by: kustomize
  name: gatewayrouter-sample
spec:
  gatewayRef:
    name: sllb-a
  interface: "vlan-100"
  address: "169.254.100.150"
  bgp:
    localASN: 64512
    remoteASN: 4200000000
    localPort: 10179
    remotePort: 10179
    holdTime: 24s
    bfd:
      switch: true
      minTx: 300ms
      minRx: 300ms
      multiplier: 3
