---
name: e2e

on:
  workflow_call:
    secrets:
      HARBOR_REGISTRY:
        required: true
      HARBOR_USERNAME:
        required: true
      HARBOR_PASSWORD:
        required: true

  workflow_dispatch:

env:
  KIND_VERSION: v0.27.0

jobs:
  get-tag:
    name: Get tag
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.get-tag-step.outputs.tag }}
    steps:
      - name: Get tag
        id: get-tag-step
        run: |
          branch="${{ github.ref_name }}"

          if [[ "$branch" == release/* ]]; then
            tag="${branch#release/}"
          elif [[ "$branch" == "master" ]]; then
            tag="latest"
          else
            tag="$branch"
          fi

          echo "tag=latest" >> $GITHUB_OUTPUT
          echo "Using tag: latest"

  e2e:
    runs-on: ubuntu-latest
    needs: get-tag
    strategy:
      fail-fast: false
      matrix:
        suite:
          - common-appnetwork
          - separate-appnetwork
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.ref_name }}
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - uses: helm/kind-action@v1
        with:
          version: ${{ env.KIND_VERSION }}
          node_image: kindest/node:v1.32.2@sha256:f226345927d7e348497136874b6d207e0b32cc52154ad8323129352923a3142f
          cluster_name: kind
          config: test/e2e/kind-cluster/kind-basic.yaml
      - uses: docker/login-action@v4
        with:
          registry: ${{ secrets.HARBOR_REGISTRY }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}
      - name: Setup cluster dependencies
        run: |
          make -C test/e2e cluster REGISTRY=${{ secrets.HARBOR_REGISTRY }}/cloud-native/meridio-2 VERSION=${{ needs.get-tag.outputs.tag }}
          docker ps
          kubectl get all -A
      - name: Deploy ${{ matrix.suite }} suite
        run: |
          make -C test/e2e deploy-${{ matrix.suite }} REGISTRY=${{ secrets.HARBOR_REGISTRY }}/cloud-native/meridio-2 VERSION=${{ needs.get-tag.outputs.tag }}
          kubectl get all -A
      - name: Run ${{ matrix.suite }} tests
        run: make -C test/e2e test-${{ matrix.suite }} REGISTRY=${{ secrets.HARBOR_REGISTRY }}/cloud-native/meridio-2 VERSION=${{ needs.get-tag.outputs.tag }}
