---
name: e2e
on:
  workflow_run:
    workflows: ["ci"]
    types:
      - completed
    branches:
      - "release/**"

env:
  KIND_VERSION: v0.27.0

jobs:
  kind:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      fail-fast: false
      matrix:
        image:
          - v1.32.2@sha256:f226345927d7e348497136874b6d207e0b32cc52154ad8323129352923a3142f
          - v1.31.6@sha256:28b7cbb993dfe093c76641a0c95807637213c9109b761f1d422c2400e22b8e87
          - v1.30.10@sha256:4de75d0e82481ea846c0ed1de86328d821c1e6a6a91ac37bf804e5313670e507
          - v1.29.14@sha256:8703bd94ee24e51b778d5556ae310c6c0fa67d761fae6379c8e0bb480e6fea29
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - uses: helm/kind-action@v1
        with:
          version: ${{ env.KIND_VERSION }}
          node_image: kindest/node:${{ matrix.image }}
          cluster_name: kind
      - name: Check cluster
        run: |
          kubectl version
          kubectl cluster-info
      - name: Build and load image
        run: |
          make controller-manager VERSION_CONTROLLER_MANAGER=e2e BUILD_STEPS=build
          kind load docker-image controller-manager:e2e --name kind
      - name: Deploy
        run: make deploy VERSION_CONTROLLER_MANAGER=e2e
      - name: List pods
        run: kubectl get pods -A
